version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - furo

sphinx:
  configuration: docs/conf.py
